// Renders assets/banner.svg: the dramatic dark "imperial" hero. The Soloviev
// family arms standing free under a segmental arch (an aedicule niche), a
// hedera rule along the foot of the wall, the name column to the right with
// staggered SMIL reveals. All text is baked to vector paths; the device is an
// embedded base64 PNG (684px, regenerated by scripts/make-arms.mjs).
//
// The device replaced a framed fresco panel in 2026-08. Three consequences
// worth knowing before editing the geometry below. Heraldry is not a picture,
// so it gets no backing rect and no frame stroke. It must never be cropped, so
// preserveAspectRatio is "meet" (fit inside) and not "slice" (crop to fill).
// And the segmental arch that used to spring over the panel is gone: it worked
// against a square, but over the ragged silhouette of mantling and plumes it
// stopped reading as architecture and started reading as a stray scratch. Both
// alternatives were rendered and compared before it came out. The aedicule
// language survives elsewhere in the family of cards.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { C, layoutLine, round, font, fontTitle, hederaRule, staticize } from './svglib.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ARMS = readFileSync(join(__dirname, 'arms.b64'), 'utf8').trim();

const W = 1000;
const H = 340;

// Banner-specific tones (dark ground, warm metals). Lifted brighter than the
// page palette for legibility of small text over the grainy dark ground.
const T = {
  cream: '#F6F1E7',
  roleCream: '#F1E7D6',
  gold: '#E3CA84',
  goldLine: '#C9A661',
  muted: '#DBD0BB',
};

const missing = [];
function lineSvg(text, x, y, size, ls, fill, { anchor = 'start', font: fnt } = {}) {
  const l = layoutLine(text, size, { letterSpacing: ls, font: fnt });
  missing.push(...l.missing);
  let dx = x;
  if (anchor === 'middle') dx = x - l.width / 2;
  else if (anchor === 'end') dx = x - l.width;
  return { width: l.width, svg: `<g fill="${fill}"><path transform="translate(${round(dx)} ${y})" d="${l.d}"/></g>` };
}

// Staggered entrance with a VISIBLE base state: the group is opacity 1 by
// default (so it shows even if SMIL never runs or a SMIL bug creeps in), and
// the intro is held at hidden for `delay` seconds via keyTimes, all begin=0s
// so there is no visible-then-hidden flash.
function fadeUp(inner, delay = 0, dy = 9) {
  if (delay > 0) {
    const dur = (0.9 + delay).toFixed(2);
    const k = (delay / (0.9 + delay)).toFixed(3);
    return `<g opacity="1">` +
      `<animate attributeName="opacity" values="0;0;1" keyTimes="0;${k};1" dur="${dur}s" begin="0s" fill="freeze" calcMode="spline" keySplines="0 0 1 1;0.22 1 0.36 1"/>` +
      `<animateTransform attributeName="transform" type="translate" values="0 ${dy};0 ${dy};0 0" keyTimes="0;${k};1" dur="${dur}s" begin="0s" fill="freeze" calcMode="spline" keySplines="0 0 1 1;0.22 1 0.36 1"/>` +
      `${inner}</g>`;
  }
  return `<g opacity="1">` +
    `<animate attributeName="opacity" from="0" to="1" dur="0.9s" begin="0s" fill="freeze"/>` +
    `<animateTransform attributeName="transform" type="translate" from="0 ${dy}" to="0 0" dur="0.9s" begin="0s" fill="freeze" calcMode="spline" keySplines="0.22 1 0.36 1" keyTimes="0;1" values="0 ${dy};0 0"/>` +
    `${inner}</g>`;
}

// Device geometry (left). Portrait, unlike the square fresco panel it replaced,
// so it is sized by HEIGHT and centred on the old panel's axis (x=172) to keep
// the composition's balance against the text column. Sized to fill the band the
// panel used to occupy: any smaller and the dark space above and below it opens
// up again. The box is a bounding box only: with preserveAspectRatio="meet" the
// arms letterbox inside it, and since nothing is painted behind them a small
// mismatch is invisible.
const DH = 264;
const DW = 220;
const DX = 172 - DW / 2;
const DY = (H - DH) / 2;

// Text column (right of panel). Sized to fill the width: the name reaches deep
// into the formerly empty right third, and the supporting lines scale with it.
// Titling (eyebrow + name) is Cinzel (Roman monumental caps); the role and the
// tagline are EB Garamond (the readable body serif). The name is fit to the
// available width so Cinzel's wider caps never overrun the right edge.
const TX = 306;
const NAME_MAXW = 960 - TX; // right edge with a small inset
const TITLE = fontTitle();
const BODY = font();

let nameSize = 62;
while (nameSize > 40 && layoutLine('ANTON SOLOVIEV', nameSize, { letterSpacing: 2.4, font: TITLE }).width > NAME_MAXW) {
  nameSize -= 1;
}

const eyebrow = lineSvg('PRAVIEL · ANCIENT LANGUAGES', TX + 2, 92, 15, 4.6, T.gold, { font: TITLE });
const name = lineSvg('ANTON SOLOVIEV', TX, 166, nameSize, 2.4, T.cream, { font: TITLE });
const role1 = lineSvg('Founder and Lead Engineer, PRAVIEL', TX + 1, 231, 25, 0.2, T.roleCream, { font: BODY });
const role2 = lineSvg('The old languages, out loud again.', TX + 1, 266, 22, 0.2, T.muted, { font: BODY });

// Describes what is visible, not a formal blazon: the arms have not been
// checked against a heraldic source and the label should not pretend otherwise.
const ARIA =
  'Anton Soloviev. Founder and Lead Engineer, PRAVIEL. The old languages, out loud again. ' +
  'Beside the name, the Soloviev family arms: an oak tree on a blue field beneath a silver ' +
  'chief bearing three bees, with a crowned helm, an anchor crest in blue plumes, and blue ' +
  'and gold mantling.';

const ulY = 186;
const ulW = name.width;

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="${ARIA}">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0.35" y2="1">
      <stop offset="0" stop-color="#17130E"/>
      <stop offset="1" stop-color="#0B0907"/>
    </linearGradient>
    <radialGradient id="crimson" cx="0.86" cy="0.1" r="0.7">
      <stop offset="0" stop-color="${C.crimson}" stop-opacity="0.30"/>
      <stop offset="0.6" stop-color="${C.crimson}" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="goldwash" cx="0.16" cy="0.92" r="0.7">
      <stop offset="0" stop-color="${C.gold}" stop-opacity="0.18"/>
      <stop offset="0.6" stop-color="${C.gold}" stop-opacity="0"/>
    </radialGradient>
    <clipPath id="bgClip"><rect width="${W}" height="${H}" rx="18"/></clipPath>
    <filter id="grain"><feTurbulence type="fractalNoise" baseFrequency="0.9" numOctaves="2" stitchTiles="stitch" result="n"/><feColorMatrix in="n" type="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.05 0"/></filter>
  </defs>

  <rect width="${W}" height="${H}" rx="18" fill="url(#bg)"/>
  <rect width="${W}" height="${H}" rx="18" fill="url(#crimson)"/>
  <rect width="${W}" height="${H}" rx="18" fill="url(#goldwash)"/>
  <rect width="${W}" height="${H}" rx="18" fill="#000" filter="url(#grain)" opacity="0.45" clip-path="url(#bgClip)"/>
  <rect x="1" y="1" width="${W - 2}" height="${H - 2}" rx="17" fill="none" stroke="${C.gold}" stroke-width="1" opacity="0.30"/>

  <!-- Hedera rule along the foot of the wall (a single Roman divider, gold leaf on the dark ground) -->
  ${hederaRule(W / 2, H - 28, 300, { stroke: T.goldLine, leaf: T.gold, size: 19, opacity: 0.6 })}

  <!-- The arms, standing free on the wall -->
  <g opacity="1"><animate attributeName="opacity" from="0" to="1" dur="1s" begin="0s" fill="freeze"/>
    <image href="${ARMS}" x="${DX}" y="${DY}" width="${DW}" height="${DH}" preserveAspectRatio="xMidYMid meet"/>
  </g>

  <!-- Text column -->
  ${fadeUp(eyebrow.svg, 0.2)}
  ${fadeUp(name.svg, 0.35)}
  <line x1="${TX}" y1="${ulY}" x2="${round(TX + ulW)}" y2="${ulY}" stroke="${T.goldLine}" stroke-width="1.6" stroke-linecap="round" stroke-dasharray="${round(ulW)}" stroke-dashoffset="0">
    <animate attributeName="stroke-dashoffset" values="${round(ulW)};${round(ulW)};0" keyTimes="0;0.4;1" dur="1.35s" begin="0s" fill="freeze" calcMode="spline" keySplines="0 0 1 1;0.22 1 0.36 1"/>
  </line>
  ${fadeUp(role1.svg, 0.7)}
  ${fadeUp(role2.svg, 0.9)}
</svg>`;

writeFileSync(join(ROOT, 'assets', 'banner.svg'), svg, 'utf8');
console.log(`banner.svg written (${svg.length} bytes). name width=${round(name.width)}`);
if (missing.length) {
  console.warn('MISSING GLYPHS:', JSON.stringify(missing));
  process.exitCode = 1;
} else console.log('All glyphs resolved (no .notdef).');

// Static QA copy (SMIL stripped; base state is already the final frame).
if (process.env.STATIC) {
  const dir = join(ROOT, '.preview');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'banner.svg'), staticize(svg), 'utf8');
}
